  [OID] wgClientDHCPClient                                                                                
  [OID] wgClientDHCPClientDNSOne                                                                          
  [OID] wgClientDHCPClientDNSTwo                                                                          
  [OID] wgClientDHCPClientDefaultGateway                                                                  
  [OID] wgClientDHCPClientDomainName                                                                      
  [OID] wgClientDHCPClientEnable                                                                          
  [OID] wgClientDHCPServer                                                                                
  [OID] wgClientDHCPServerConnClientHostName                                                              
  [OID] wgClientDHCPServerConnEntry                                                                       
  [OID] wgClientDHCPServerConnIPAddr                                                                      
  [OID] wgClientDHCPServerConnLeaseTimeEnd                                                                
  [OID] wgClientDHCPServerConnLeaseTimeStart                                                              
  [OID] wgClientDHCPServerConnMACAddr                                                                     
  [OID] wgClientDHCPServerConnTable                                                                       
  [OID] wgClientDHCPServerEnable                                                                          
  [OID] wgClientDHCPServerEndIpAddress                                                                    
  [OID] wgClientDHCPServerLeaseTime                                                                       
  [OID] wgClientDHCPServerNum                                                                             
  [OID] wgClientDHCPServerRelayServer                                                                     
  [OID] wgClientDHCPServerStartIpAddress                                                                  
  [OID] wgClientMIB                                                                                       
  [OID] wgClientPPPoEADSLPeerMACAddr                                                                      
  [OID] wgClientPPPoEClient                                                                               
  [OID] wgClientPPPoEClientADSLStatus                                                                     
  [OID] wgClientPPPoEClientConnTime                                                                       
  [OID] wgClientPPPoEClientDNSOne                                                                         
  [OID] wgClientPPPoEClientDNSTwo                                                                         
  [OID] wgClientPPPoEClientEnable                                                                         
  [OID] wgClientPPPoEClientLocalIPAddr                                                                    
  [OID] wgClientPPPoEClientNetMask                                                                        
  [OID] wgClientPPPoEClientRemoteIPAddr                                                                   
  [OID] wgInfoModule                                                                                      
  [OID] .1.3.6.1.4.1.3097.6                                                                               
  [OID] .1.3.6.1.4.1.3097.6.2                                                                             
  [OID] .1.3.6.1.4.1.3097.6.2.1                                                                           
  [OID] .1.3.6.1.4.1.3097.6.2.1.1                                                                         
  [OID] .1.3.6.1.4.1.3097.6.2.1.2                                                                         
  [OID] .1.3.6.1.4.1.3097.6.2.1.3                                                                         
  [OID] .1.3.6.1.4.1.3097.6.2.1.4                                                                         
  [OID] .1.3.6.1.4.1.3097.6.2.1.5                                                                         
  [OID] .1.3.6.1.4.1.3097.6.2.1.6                                                                         
  [OID] .1.3.6.1.4.1.3097.6.2.1.6.1                                                                       
  [OID] .1.3.6.1.4.1.3097.6.2.1.6.1.1                                                                     
  [OID] .1.3.6.1.4.1.3097.6.2.1.6.1.2                                                                     
  [OID] .1.3.6.1.4.1.3097.6.2.1.6.1.3                                                                     
  [OID] .1.3.6.1.4.1.3097.6.2.1.6.1.4                                                                     
  [OID] .1.3.6.1.4.1.3097.6.2.1.6.1.5                                                                     
  [OID] .1.3.6.1.4.1.3097.6.2.1.7                                                                         
  [OID] .1.3.6.1.4.1.3097.6.2.2                                                                           
  [OID] .1.3.6.1.4.1.3097.6.2.2.1                                                                         
  [OID] .1.3.6.1.4.1.3097.6.2.2.2                                                                         
  [OID] .1.3.6.1.4.1.3097.6.2.2.3                                                                         
  [OID] .1.3.6.1.4.1.3097.6.2.2.4                                                                         
  [OID] .1.3.6.1.4.1.3097.6.2.2.5                                                                         
  [OID] .1.3.6.1.4.1.3097.6.2.3                                                                           
  [OID] .1.3.6.1.4.1.3097.6.2.3.1                                                                         
  [OID] .1.3.6.1.4.1.3097.6.2.3.2                                                                         
  [OID] .1.3.6.1.4.1.3097.6.2.3.3                                                                         
  [OID] .1.3.6.1.4.1.3097.6.2.3.4                                                                         
  [OID] .1.3.6.1.4.1.3097.6.2.3.5                                                                         
  [OID] .1.3.6.1.4.1.3097.6.2.3.6                                                                         
  [OID] .1.3.6.1.4.1.3097.6.2.3.7                                                                         
  [OID] .1.3.6.1.4.1.3097.6.2.3.8                                                                         
  [OID] .1.3.6.1.4.1.3097.6.2.3.9                                                                         
  [OID] enterprises.3097.6                                                                                
  [OID] enterprises.3097.6.2                                                                              
  [OID] enterprises.3097.6.2.1                                                                            
  [OID] enterprises.3097.6.2.1.1                                                                          
  [OID] enterprises.3097.6.2.1.2                                                                          
  [OID] enterprises.3097.6.2.1.3                                                                          
  [OID] enterprises.3097.6.2.1.4                                                                          
  [OID] enterprises.3097.6.2.1.5                                                                          
  [OID] enterprises.3097.6.2.1.6                                                                          
  [OID] enterprises.3097.6.2.1.6.1                                                                        
  [OID] enterprises.3097.6.2.1.6.1.1                                                                      
  [OID] enterprises.3097.6.2.1.6.1.2                                                                      
  [OID] enterprises.3097.6.2.1.6.1.3                                                                      
  [OID] enterprises.3097.6.2.1.6.1.4                                                                      
  [OID] enterprises.3097.6.2.1.6.1.5                                                                      
  [OID] enterprises.3097.6.2.1.7                                                                          
  [OID] enterprises.3097.6.2.2                                                                            
  [OID] enterprises.3097.6.2.2.1                                                                          
  [OID] enterprises.3097.6.2.2.2                                                                          
  [OID] enterprises.3097.6.2.2.3                                                                          
  [OID] enterprises.3097.6.2.2.4                                                                          
  [OID] enterprises.3097.6.2.2.5                                                                          
  [OID] enterprises.3097.6.2.3                                                                            
  [OID] enterprises.3097.6.2.3.1                                                                          
  [OID] enterprises.3097.6.2.3.2                                                                          
  [OID] enterprises.3097.6.2.3.3                                                                          
  [OID] enterprises.3097.6.2.3.4                                                                          
  [OID] enterprises.3097.6.2.3.5                                                                          
  [OID] enterprises.3097.6.2.3.6                                                                          
  [OID] enterprises.3097.6.2.3.7                                                                          
  [OID] enterprises.3097.6.2.3.8                                                                          
  [OID] enterprises.3097.6.2.3.9                                                                          
