  [OID] wgPolicyActiveStreams                                                                             
  [OID] wgPolicyBytes                                                                                     
  [OID] wgPolicyCurrActiveConns                                                                           
  [OID] wgPolicyDisc                                                                                      
  [OID] wgPolicyEntry                                                                                     
  [OID] wgPolicyFwDisc                                                                                    
  [OID] wgPolicyID                                                                                        
  [OID] wgPolicyIpsecAuthErr                                                                              
  [OID] wgPolicyIpsecDecryptErr                                                                           
  [OID] wgPolicyIpsecDisc                                                                                 
  [OID] wgPolicyIpsecPadErr                                                                               
  [OID] wgPolicyIpsecPolicyErr                                                                            
  [OID] wgPolicyIpsecReplayErr                                                                            
  [OID] wgPolicyLogging                                                                                   
  [OID] wgPolicyMIB                                                                                       
  [OID] wgPolicyName                                                                                      
  [OID] wgPolicyNumTunl                                                                                   
  [OID] wgPolicyOtherDisc                                                                                 
  [OID] wgPolicyPackets                                                                                   
  [OID] wgPolicySingleCntrNum                                                                             
  [OID] wgPolicyStatistics                                                                                
  [OID] wgPolicyTable                                                                                     
  [OID] wgPolicyTableNum                                                                                  
  [OID] wgPolicyToTunnel                                                                                  
  [OID] wgPolicyToTunnelEntry                                                                             
  [OID] wgPolicyToTunnelNum                                                                               
  [OID] wgPolicyToTunnelPolicyID                                                                          
  [OID] wgPolicyToTunnelTable                                                                             
  [OID] wgPolicyToTunnelTunnelID                                                                          
  [OID] .1.3.6.1.4.1.3097.4                                                                               
  [OID] .1.3.6.1.4.1.3097.4.1                                                                             
  [OID] .1.3.6.1.4.1.3097.4.1.1                                                                           
  [OID] .1.3.6.1.4.1.3097.4.1.2                                                                           
  [OID] .1.3.6.1.4.1.3097.4.1.2.1                                                                         
  [OID] .1.3.6.1.4.1.3097.4.1.2.1.1                                                                       
  [OID] .1.3.6.1.4.1.3097.4.1.2.1.2                                                                       
  [OID] .1.3.6.1.4.1.3097.4.2                                                                             
  [OID] .1.3.6.1.4.1.3097.4.2.1                                                                           
  [OID] .1.3.6.1.4.1.3097.4.2.2                                                                           
  [OID] .1.3.6.1.4.1.3097.4.2.2.1                                                                         
  [OID] .1.3.6.1.4.1.3097.4.2.2.1.1                                                                       
  [OID] .1.3.6.1.4.1.3097.4.2.2.1.2                                                                       
  [OID] .1.3.6.1.4.1.3097.4.2.2.1.3                                                                       
  [OID] .1.3.6.1.4.1.3097.4.2.2.1.4                                                                       
  [OID] .1.3.6.1.4.1.3097.4.2.2.1.5                                                                       
  [OID] .1.3.6.1.4.1.3097.4.2.2.1.6                                                                       
  [OID] .1.3.6.1.4.1.3097.4.2.2.1.7                                                                       
  [OID] .1.3.6.1.4.1.3097.4.2.2.1.8                                                                       
  [OID] .1.3.6.1.4.1.3097.4.2.2.1.9                                                                       
  [OID] .1.3.6.1.4.1.3097.4.2.2.1.10                                                                      
  [OID] .1.3.6.1.4.1.3097.4.2.2.1.11                                                                      
  [OID] .1.3.6.1.4.1.3097.4.2.2.1.12                                                                      
  [OID] .1.3.6.1.4.1.3097.4.2.2.1.13                                                                      
  [OID] .1.3.6.1.4.1.3097.4.2.2.1.14                                                                      
  [OID] .1.3.6.1.4.1.3097.4.2.2.1.15                                                                      
  [OID] .1.3.6.1.4.1.3097.4.2.2.1.16                                                                      
  [OID] .1.3.6.1.4.1.3097.4.2.2.1.17                                                                      
  [OID] .1.3.6.1.4.1.3097.4.2.2.1.18                                                                      
  [OID] enterprises.3097.4                                                                                
  [OID] enterprises.3097.4.1                                                                              
  [OID] enterprises.3097.4.1.1                                                                            
  [OID] enterprises.3097.4.1.2                                                                            
  [OID] enterprises.3097.4.1.2.1                                                                          
  [OID] enterprises.3097.4.1.2.1.1                                                                        
  [OID] enterprises.3097.4.1.2.1.2                                                                        
  [OID] enterprises.3097.4.2                                                                              
  [OID] enterprises.3097.4.2.1                                                                            
  [OID] enterprises.3097.4.2.2                                                                            
  [OID] enterprises.3097.4.2.2.1                                                                          
  [OID] enterprises.3097.4.2.2.1.1                                                                        
  [OID] enterprises.3097.4.2.2.1.2                                                                        
  [OID] enterprises.3097.4.2.2.1.3                                                                        
  [OID] enterprises.3097.4.2.2.1.4                                                                        
  [OID] enterprises.3097.4.2.2.1.5                                                                        
  [OID] enterprises.3097.4.2.2.1.6                                                                        
  [OID] enterprises.3097.4.2.2.1.7                                                                        
  [OID] enterprises.3097.4.2.2.1.8                                                                        
  [OID] enterprises.3097.4.2.2.1.9                                                                        
  [OID] enterprises.3097.4.2.2.1.10                                                                       
  [OID] enterprises.3097.4.2.2.1.11                                                                       
  [OID] enterprises.3097.4.2.2.1.12                                                                       
  [OID] enterprises.3097.4.2.2.1.13                                                                       
  [OID] enterprises.3097.4.2.2.1.14                                                                       
  [OID] enterprises.3097.4.2.2.1.15                                                                       
  [OID] enterprises.3097.4.2.2.1.16                                                                       
  [OID] enterprises.3097.4.2.2.1.17                                                                       
  [OID] enterprises.3097.4.2.2.1.18                                                                       
