  [OID] wgInfoModule                                                                                           
  [OID] wgInfoSystem                                                                                           
  [OID] wgInfoSystemCurrentTime                                                                                
  [OID] .1.3.6.1.4.1.3097.6                                                                                    
  [OID] .1.3.6.1.4.1.3097.6.1                                                                                  
  [OID] .1.3.6.1.4.1.3097.6.1.1                                                                                
  [OID] enterprises.3097.6                                                                                     
  [OID] enterprises.3097.6.1                                                                                   
  [OID] enterprises.3097.6.1.1                                                                                 
