  [OID] wgInfoModule                                                                                            
  [OID] wgIpsecTunnel                                                                                           
  [OID] wgIpsecTunnelAccSecs                                                                                    
  [OID] wgIpsecTunnelAhAuthAlg                                                                                  
  [OID] wgIpsecTunnelCreateTime                                                                                 
  [OID] wgIpsecTunnelDeviceID                                                                                   
  [OID] wgIpsecTunnelEntry                                                                                      
  [OID] wgIpsecTunnelEspAuthAlg                                                                                 
  [OID] wgIpsecTunnelEspEncryptAlg                                                                              
  [OID] wgIpsecTunnelID                                                                                         
  [OID] wgIpsecTunnelInAuthErrors                                                                               
  [OID] wgIpsecTunnelInDecryptErrors                                                                            
  [OID] wgIpsecTunnelInKbytes                                                                                   
  [OID] wgIpsecTunnelInOtherErrors                                                                              
  [OID] wgIpsecTunnelInPackets                                                                                  
  [OID] wgIpsecTunnelInReplayErrors                                                                             
  [OID] wgIpsecTunnelInSaBytes                                                                                  
  [OID] wgIpsecTunnelInSpi                                                                                      
  [OID] wgIpsecTunnelKeyMode                                                                                    
  [OID] wgIpsecTunnelLifeLength                                                                                 
  [OID] wgIpsecTunnelLifeTime                                                                                   
  [OID] wgIpsecTunnelLocalAddr                                                                                  
  [OID] wgIpsecTunnelMIB                                                                                        
  [OID] wgIpsecTunnelMode                                                                                       
  [OID] wgIpsecTunnelNum                                                                                        
  [OID] wgIpsecTunnelNumRekey                                                                                   
  [OID] wgIpsecTunnelOrigPeerAddr                                                                               
  [OID] wgIpsecTunnelOutAuthErrors                                                                              
  [OID] wgIpsecTunnelOutDecryptErrors                                                                           
  [OID] wgIpsecTunnelOutKbytes                                                                                  
  [OID] wgIpsecTunnelOutOtherErrors                                                                             
  [OID] wgIpsecTunnelOutPackets                                                                                 
  [OID] wgIpsecTunnelOutReplayErrors                                                                            
  [OID] wgIpsecTunnelOutSaBytes                                                                                 
  [OID] wgIpsecTunnelOutSpi                                                                                     
  [OID] wgIpsecTunnelPeerAddr                                                                                   
  [OID] wgIpsecTunnelPeerUdpPort                                                                                
  [OID] wgIpsecTunnelSelectorLocalIPOne                                                                         
  [OID] wgIpsecTunnelSelectorLocalIPTwo                                                                         
  [OID] wgIpsecTunnelSelectorLocalIPType                                                                        
  [OID] wgIpsecTunnelSelectorLocalPort                                                                          
  [OID] wgIpsecTunnelSelectorProtocol                                                                           
  [OID] wgIpsecTunnelSelectorRemoteIPOne                                                                        
  [OID] wgIpsecTunnelSelectorRemoteIPTwo                                                                        
  [OID] wgIpsecTunnelSelectorRemoteIPType                                                                       
  [OID] wgIpsecTunnelSelectorRemotePort                                                                         
  [OID] wgIpsecTunnelTable                                                                                      
  [OID] wgIpsecTunnelUdpEncap                                                                                   
  [OID] .1.3.6.1.4.1.3097.6                                                                                     
  [OID] .1.3.6.1.4.1.3097.6.5                                                                                   
  [OID] .1.3.6.1.4.1.3097.6.5.1                                                                                 
  [OID] .1.3.6.1.4.1.3097.6.5.1.1                                                                               
  [OID] .1.3.6.1.4.1.3097.6.5.1.2                                                                               
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1                                                                             
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.1                                                                           
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.2                                                                           
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.3                                                                           
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.4                                                                           
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.5                                                                           
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.6                                                                           
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.7                                                                           
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.8                                                                           
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.9                                                                           
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.10                                                                          
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.11                                                                          
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.12                                                                          
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.13                                                                          
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.14                                                                          
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.15                                                                          
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.16                                                                          
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.17                                                                          
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.18                                                                          
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.19                                                                          
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.20                                                                          
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.21                                                                          
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.22                                                                          
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.23                                                                          
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.24                                                                          
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.25                                                                          
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.26                                                                          
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.27                                                                          
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.28                                                                          
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.29                                                                          
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.30                                                                          
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.31                                                                          
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.32                                                                          
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.33                                                                          
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.34                                                                          
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.35                                                                          
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.36                                                                          
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.37                                                                          
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.38                                                                          
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.39                                                                          
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.40                                                                          
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.41                                                                          
  [OID] .1.3.6.1.4.1.3097.6.5.1.2.1.42                                                                          
  [OID] enterprises.3097.6                                                                                      
  [OID] enterprises.3097.6.5                                                                                    
  [OID] enterprises.3097.6.5.1                                                                                  
  [OID] enterprises.3097.6.5.1.1                                                                                
  [OID] enterprises.3097.6.5.1.2                                                                                
  [OID] enterprises.3097.6.5.1.2.1                                                                              
  [OID] enterprises.3097.6.5.1.2.1.1                                                                            
  [OID] enterprises.3097.6.5.1.2.1.2                                                                            
  [OID] enterprises.3097.6.5.1.2.1.3                                                                            
  [OID] enterprises.3097.6.5.1.2.1.4                                                                            
  [OID] enterprises.3097.6.5.1.2.1.5                                                                            
  [OID] enterprises.3097.6.5.1.2.1.6                                                                            
  [OID] enterprises.3097.6.5.1.2.1.7                                                                            
  [OID] enterprises.3097.6.5.1.2.1.8                                                                            
  [OID] enterprises.3097.6.5.1.2.1.9                                                                            
  [OID] enterprises.3097.6.5.1.2.1.10                                                                           
  [OID] enterprises.3097.6.5.1.2.1.11                                                                           
  [OID] enterprises.3097.6.5.1.2.1.12                                                                           
  [OID] enterprises.3097.6.5.1.2.1.13                                                                           
  [OID] enterprises.3097.6.5.1.2.1.14                                                                           
  [OID] enterprises.3097.6.5.1.2.1.15                                                                           
  [OID] enterprises.3097.6.5.1.2.1.16                                                                           
  [OID] enterprises.3097.6.5.1.2.1.17                                                                           
  [OID] enterprises.3097.6.5.1.2.1.18                                                                           
  [OID] enterprises.3097.6.5.1.2.1.19                                                                           
  [OID] enterprises.3097.6.5.1.2.1.20                                                                           
  [OID] enterprises.3097.6.5.1.2.1.21                                                                           
  [OID] enterprises.3097.6.5.1.2.1.22                                                                           
  [OID] enterprises.3097.6.5.1.2.1.23                                                                           
  [OID] enterprises.3097.6.5.1.2.1.24                                                                           
  [OID] enterprises.3097.6.5.1.2.1.25                                                                           
  [OID] enterprises.3097.6.5.1.2.1.26                                                                           
  [OID] enterprises.3097.6.5.1.2.1.27                                                                           
  [OID] enterprises.3097.6.5.1.2.1.28                                                                           
  [OID] enterprises.3097.6.5.1.2.1.29                                                                           
  [OID] enterprises.3097.6.5.1.2.1.30                                                                           
  [OID] enterprises.3097.6.5.1.2.1.31                                                                           
  [OID] enterprises.3097.6.5.1.2.1.32                                                                           
  [OID] enterprises.3097.6.5.1.2.1.33                                                                           
  [OID] enterprises.3097.6.5.1.2.1.34                                                                           
  [OID] enterprises.3097.6.5.1.2.1.35                                                                           
  [OID] enterprises.3097.6.5.1.2.1.36                                                                           
  [OID] enterprises.3097.6.5.1.2.1.37                                                                           
  [OID] enterprises.3097.6.5.1.2.1.38                                                                           
  [OID] enterprises.3097.6.5.1.2.1.39                                                                           
  [OID] enterprises.3097.6.5.1.2.1.40                                                                           
  [OID] enterprises.3097.6.5.1.2.1.41                                                                           
  [OID] enterprises.3097.6.5.1.2.1.42                                                                           
