  [OID] fbX1000                                                                                    
  [OID] fbX1250e                                                                                   
  [OID] fbX1250e-4                                                                                 
  [OID] fbX2500                                                                                    
  [OID] fbX500                                                                                     
  [OID] fbX5000                                                                                    
  [OID] fbX5500e                                                                                   
  [OID] fbX550e                                                                                    
  [OID] fbX6000                                                                                    
  [OID] fbX6500e                                                                                   
  [OID] fbX700                                                                                     
  [OID] fbX750e                                                                                    
  [OID] fbX750e-4                                                                                  
  [OID] fbX8000                                                                                    
  [OID] fbX8500e                                                                                   
  [OID] fbX8500e-F                                                                                 
  [OID] fbXSeries                                                                                  
  [OID] watchguard                                                                                 
  [OID] wgProducts                                                                                 
  [OID] .1.3.6.1.4.1.3097                                                                          
  [OID] .1.3.6.1.4.1.3097.1                                                                        
  [OID] .1.3.6.1.4.1.3097.1.4                                                                      
  [OID] .1.3.6.1.4.1.3097.1.4.1                                                                    
  [OID] .1.3.6.1.4.1.3097.1.4.2                                                                    
  [OID] .1.3.6.1.4.1.3097.1.4.3                                                                    
  [OID] .1.3.6.1.4.1.3097.1.4.4                                                                    
  [OID] .1.3.6.1.4.1.3097.1.4.5                                                                    
  [OID] .1.3.6.1.4.1.3097.1.4.6                                                                    
  [OID] .1.3.6.1.4.1.3097.1.4.7                                                                    
  [OID] .1.3.6.1.4.1.3097.1.4.8                                                                    
  [OID] .1.3.6.1.4.1.3097.1.4.9                                                                    
  [OID] .1.3.6.1.4.1.3097.1.4.10                                                                   
  [OID] .1.3.6.1.4.1.3097.1.4.11                                                                   
  [OID] .1.3.6.1.4.1.3097.1.4.12                                                                   
  [OID] .1.3.6.1.4.1.3097.1.4.13                                                                   
  [OID] .1.3.6.1.4.1.3097.1.4.14                                                                   
  [OID] .1.3.6.1.4.1.3097.1.4.15                                                                   
  [OID] .1.3.6.1.4.1.3097.1.4.16                                                                   
  [OID] enterprises.3097                                                                           
  [OID] enterprises.3097.1                                                                         
  [OID] enterprises.3097.1.4                                                                       
  [OID] enterprises.3097.1.4.1                                                                     
  [OID] enterprises.3097.1.4.2                                                                     
  [OID] enterprises.3097.1.4.3                                                                     
  [OID] enterprises.3097.1.4.4                                                                     
  [OID] enterprises.3097.1.4.5                                                                     
  [OID] enterprises.3097.1.4.6                                                                     
  [OID] enterprises.3097.1.4.7                                                                     
  [OID] enterprises.3097.1.4.8                                                                     
  [OID] enterprises.3097.1.4.9                                                                     
  [OID] enterprises.3097.1.4.10                                                                    
  [OID] enterprises.3097.1.4.11                                                                    
  [OID] enterprises.3097.1.4.12                                                                    
  [OID] enterprises.3097.1.4.13                                                                    
  [OID] enterprises.3097.1.4.14                                                                    
  [OID] enterprises.3097.1.4.15                                                                    
  [OID] enterprises.3097.1.4.16                                                                    
