  [OID] wgInfoModule
  [OID] wgSystemCpuUtil
  [OID] wgSystemCpuUtil1
  [OID] wgSystemCpuUtil15
  [OID] wgSystemCpuUtil5
  [OID] wgSystemCurrActiveConns
  [OID] wgSystemStatisticsMIB
  [OID] wgSystemStreamReqDrop
  [OID] wgSystemStreamReqTotal
  [OID] wgSystemTotalRecvBytes
  [OID] wgSystemTotalRecvPackets
  [OID] wgSystemTotalSendBytes
  [OID] wgSystemTotalSendPackets
  [OID] .1.3.6.1.4.1.3097.6
  [OID] .1.3.6.1.4.1.3097.6.3
  [OID] .1.3.6.1.4.1.3097.6.3.4
  [OID] .1.3.6.1.4.1.3097.6.3.8
  [OID] .1.3.6.1.4.1.3097.6.3.9
  [OID] .1.3.6.1.4.1.3097.6.3.10
  [OID] .1.3.6.1.4.1.3097.6.3.11
  [OID] .1.3.6.1.4.1.3097.6.3.30
  [OID] .1.3.6.1.4.1.3097.6.3.34
  [OID] .1.3.6.1.4.1.3097.6.3.77
  [OID] .1.3.6.1.4.1.3097.6.3.78
  [OID] .1.3.6.1.4.1.3097.6.3.79
  [OID] .1.3.6.1.4.1.3097.6.3.80
  [OID] enterprises.3097.6
  [OID] enterprises.3097.6.3
  [OID] enterprises.3097.6.3.4
  [OID] enterprises.3097.6.3.8
  [OID] enterprises.3097.6.3.9
  [OID] enterprises.3097.6.3.10
  [OID] enterprises.3097.6.3.11
  [OID] enterprises.3097.6.3.30
  [OID] enterprises.3097.6.3.34
  [OID] enterprises.3097.6.3.77
  [OID] enterprises.3097.6.3.78
  [OID] enterprises.3097.6.3.79
  [OID] enterprises.3097.6.3.80
