  [OID] wgHAError                                                                                     
  [OID] wgHALastDBSyncTime                                                                            
  [OID] wgHALocal                                                                                     
  [OID] wgHAMIB                                                                                       
  [OID] wgHAPeer                                                                                      
  [OID] wgHAPeerCounters                                                                              
  [OID] wgHAPeerDevice                                                                                
  [OID] wgHAPeerError                                                                                 
  [OID] wgHAPeerIfEntry                                                                               
  [OID] wgHAPeerIfIndex                                                                               
  [OID] wgHAPeerIfIpAddr                                                                              
  [OID] wgHAPeerIfLinkStatus                                                                          
  [OID] wgHAPeerIfNumber                                                                              
  [OID] wgHAPeerIfTable                                                                               
  [OID] wgHAPeerLastDBSyncTime                                                                        
  [OID] wgHAPeerSerialNumber                                                                          
  [OID] wgHAPeerStatus                                                                                
  [OID] wgHAPeerSystemCpuUtil                                                                         
  [OID] wgHAPeerSystemCpuUtil1                                                                        
  [OID] wgHAPeerSystemCpuUtil15                                                                       
  [OID] wgHAPeerSystemCpuUtil5                                                                        
  [OID] wgHAPeerSystemCurrIpsecTunnels                                                                
  [OID] wgHAPeerSystemStreamReqDrop                                                                   
  [OID] wgHAPeerSystemStreamReqTotal                                                                  
  [OID] wgHAPeerSystemTotalRecvBytes                                                                  
  [OID] wgHAPeerSystemTotalRecvPackets                                                                
  [OID] wgHAPeerSystemTotalSendBytes                                                                  
  [OID] wgHAPeerSystemTotalSendPackets                                                                
  [OID] wgHAStatus                                                                                    
  [OID] wgInfoModule                                                                                  
  [OID] .1.3.6.1.4.1.3097.6                                                                           
  [OID] .1.3.6.1.4.1.3097.6.6                                                                         
  [OID] .1.3.6.1.4.1.3097.6.6.1                                                                       
  [OID] .1.3.6.1.4.1.3097.6.6.1.1                                                                     
  [OID] .1.3.6.1.4.1.3097.6.6.1.2                                                                     
  [OID] .1.3.6.1.4.1.3097.6.6.1.3                                                                     
  [OID] .1.3.6.1.4.1.3097.6.6.1.4                                                                     
  [OID] .1.3.6.1.4.1.3097.6.6.1.5                                                                     
  [OID] .1.3.6.1.4.1.3097.6.6.2                                                                       
  [OID] .1.3.6.1.4.1.3097.6.6.2.1                                                                     
  [OID] .1.3.6.1.4.1.3097.6.6.2.2                                                                     
  [OID] .1.3.6.1.4.1.3097.6.6.2.3                                                                     
  [OID] .1.3.6.1.4.1.3097.6.6.2.3.1                                                                   
  [OID] .1.3.6.1.4.1.3097.6.6.2.3.2                                                                   
  [OID] .1.3.6.1.4.1.3097.6.6.2.3.2.1                                                                 
  [OID] .1.3.6.1.4.1.3097.6.6.2.3.2.1.1                                                               
  [OID] .1.3.6.1.4.1.3097.6.6.2.3.2.1.4                                                               
  [OID] .1.3.6.1.4.1.3097.6.6.2.3.2.1.9                                                               
  [OID] .1.3.6.1.4.1.3097.6.6.2.4                                                                     
  [OID] .1.3.6.1.4.1.3097.6.6.2.4.1                                                                   
  [OID] .1.3.6.1.4.1.3097.6.6.2.4.2                                                                   
  [OID] .1.3.6.1.4.1.3097.6.6.2.4.3                                                                   
  [OID] .1.3.6.1.4.1.3097.6.6.2.4.4                                                                   
  [OID] .1.3.6.1.4.1.3097.6.6.2.4.5                                                                   
  [OID] .1.3.6.1.4.1.3097.6.6.2.4.6                                                                   
  [OID] .1.3.6.1.4.1.3097.6.6.2.4.7                                                                   
  [OID] .1.3.6.1.4.1.3097.6.6.2.4.8                                                                   
  [OID] .1.3.6.1.4.1.3097.6.6.2.4.9                                                                   
  [OID] .1.3.6.1.4.1.3097.6.6.2.4.10                                                                  
  [OID] .1.3.6.1.4.1.3097.6.6.2.4.11                                                                  
  [OID] enterprises.3097.6                                                                            
  [OID] enterprises.3097.6.6                                                                          
  [OID] enterprises.3097.6.6.1                                                                        
  [OID] enterprises.3097.6.6.1.1                                                                      
  [OID] enterprises.3097.6.6.1.2                                                                      
  [OID] enterprises.3097.6.6.1.3                                                                      
  [OID] enterprises.3097.6.6.1.4                                                                      
  [OID] enterprises.3097.6.6.1.5                                                                      
  [OID] enterprises.3097.6.6.2                                                                        
  [OID] enterprises.3097.6.6.2.1                                                                      
  [OID] enterprises.3097.6.6.2.2                                                                      
  [OID] enterprises.3097.6.6.2.3                                                                      
  [OID] enterprises.3097.6.6.2.3.1                                                                    
  [OID] enterprises.3097.6.6.2.3.2                                                                    
  [OID] enterprises.3097.6.6.2.3.2.1                                                                  
  [OID] enterprises.3097.6.6.2.3.2.1.1                                                                
  [OID] enterprises.3097.6.6.2.3.2.1.4                                                                
  [OID] enterprises.3097.6.6.2.3.2.1.9                                                                
  [OID] enterprises.3097.6.6.2.4                                                                      
  [OID] enterprises.3097.6.6.2.4.1                                                                    
  [OID] enterprises.3097.6.6.2.4.2                                                                    
  [OID] enterprises.3097.6.6.2.4.3                                                                    
  [OID] enterprises.3097.6.6.2.4.4                                                                    
  [OID] enterprises.3097.6.6.2.4.5                                                                    
  [OID] enterprises.3097.6.6.2.4.6                                                                    
  [OID] enterprises.3097.6.6.2.4.7                                                                    
  [OID] enterprises.3097.6.6.2.4.8                                                                    
  [OID] enterprises.3097.6.6.2.4.9                                                                    
  [OID] enterprises.3097.6.6.2.4.10                                                                   
  [OID] enterprises.3097.6.6.2.4.11                                                                   
